user:
  name:
    max_length: 50
  email:
    max_length: 50
  phone:
    max_length: 12
  date_of_birth:
    max_length: 10
  password:
    min_length: 6
  password:
    min_length: 6
  address:
    max_length: 255
comment:
  min_length: 1
  max_length: 255
product:
  name:
    max_length: 100
  limit: 4
  min_price: 100000
  max_price: 100000000
  min_quantity: 1
  max_quantity: 100
  lastest_product: 4
  lastest_month: 1
  image_size: [500, 500]
home:
  limit: 3
paginate:
  comment_perpage: 5
  product_perpage: 2
admin:
  list:
    per_page: 12
cart:
  item_id_default: 1
  default_quantity: 1
